-- MySQL Script generated by MySQL Workbench
-- Wed May  7 21:19:39 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library_db` DEFAULT CHARACTER SET utf8 ;
USE `library_db` ;

-- -----------------------------------------------------
-- Table `library_db`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `phone` CHAR(11) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `street` VARCHAR(75) NULL,
  `number` INT NULL,
  `complement` VARCHAR(20) NULL,
  `birthdate` DATE NULL,
  `status` ENUM("inadimplente", "bloqueado", "suspenso", "ok") NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`sessions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bookcase` INT NOT NULL,
  `starting_corridor` INT NULL,
  `ending_corridor` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`publishers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `fundation_year` SMALLINT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`employees` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `role` ENUM("Gerente", "supervisor", "Auxiliar", "estagiário") NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `phone` CHAR(11) NOT NULL,
  `residence_file_path` VARCHAR(100) NOT NULL,
  `pis` VARCHAR(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`rentals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`rentals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `withdrawal_date` DATETIME NOT NULL,
  `planned_date` DATE NOT NULL,
  `ruterned_date` DATETIME NULL,
  `status` ENUM("emprestado", "devolvido", "atrasado", "perdido") NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `client_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`, `employee_id`),
  INDEX `fk_rentals_clients_idx` (`client_id` ASC),
  INDEX `fk_rentals_employees1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_rentals_clients`
    FOREIGN KEY (`client_id`)
    REFERENCES `library_db`.`clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rentals_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `library_db`.`employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


-- -----------------------------------------------------
-- Table `library_db`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`authors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `birthdate` DATE NULL,
  `death_date` DATE NULL,
  `nationality` VARCHAR(20) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`aliases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`aliases` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`id`, `author_id`),
  INDEX `fk_aliases_authors1_idx` (`author_id` ASC),
  CONSTRAINT `fk_aliases_authors1`
    FOREIGN KEY (`author_id`)
    REFERENCES `library_db`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`pieces`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`pieces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tittle` VARCHAR(100) NOT NULL,
  `pages` INT NULL,
  `published_year` SMALLINT UNSIGNED NOT NULL,
  `category` VARCHAR(20) NOT NULL,
  `is_scanned` BINARY(1) NULL,
  `edition` VARCHAR(50) NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `languege` VARCHAR(10) NOT NULL,
  `cover` ENUM("Hardcover", "Softcover", "wireo", "Dustjacket") NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `publisher_id` INT NOT NULL,
  `aliase_id` INT NOT NULL,
  PRIMARY KEY (`id`, `publisher_id`, `aliase_id`),
  INDEX `fk_pieces_publishers1_idx` (`publisher_id` ASC),
  INDEX `fk_pieces_aliases1_idx` (`aliase_id` ASC),
  CONSTRAINT `fk_pieces_publishers1`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `library_db`.`publishers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pieces_aliases1`
    FOREIGN KEY (`aliase_id`)
    REFERENCES `library_db`.`aliases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`volumes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`volumes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bought_date` DATE NOT NULL,
  `status` ENUM("alocado", "perdido", "guardados", "não alocavel") NOT NULL,
  `printing_year` SMALLINT UNSIGNED NOT NULL,
  `condition` ENUM("Novo", "Boas condições", "Parcialmente danificado", "Danificado", "impréstimo inviável") NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `piece_id` INT NOT NULL,
  `session_id` INT NOT NULL,
  PRIMARY KEY (`id`, `piece_id`, `session_id`),
  INDEX `fk_volumn_pieces1_idx` (`piece_id` ASC),
  INDEX `fk_volumn_session1_idx` (`session_id` ASC),
  CONSTRAINT `fk_volumn_pieces1`
    FOREIGN KEY (`piece_id`)
    REFERENCES `library_db`.`pieces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_volumn_session1`
    FOREIGN KEY (`session_id`)
    REFERENCES `library_db`.`sessions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library_db`.`volumes_rentals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `library_db`.`volumes_rentals` (
  `volume_id` INT NOT NULL,
  `rental_id` INT NOT NULL,
  PRIMARY KEY (`volume_id`, `rental_id`),
  INDEX `fk_volumn_has_rentals_rentals1_idx` (`rental_id` ASC),
  INDEX `fk_volumn_has_rentals_volumn1_idx` (`volume_id` ASC),
  CONSTRAINT `fk_volumn_has_rentals_volumn1`
    FOREIGN KEY (`volume_id`)
    REFERENCES `library_db`.`volumes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_volumn_has_rentals_rentals1`
    FOREIGN KEY (`rental_id`)
    REFERENCES `library_db`.`rentals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
